# permissions for end users to view mysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-viewer-role
rules:
- apiGroups:
  - database.erda.cloud
  resources:
  - mysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.erda.cloud
  resources:
  - mysqls/status
  verbs:
  - get
